name: Ganga GSoC Tests

on:
  push:
    paths:
      - 'src/gangagsoc/**'
  pull_request:
    paths:
      - 'src/gangagsoc/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/gangagsoc
        
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y poppler-utils

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linting
      run: |
        pylint $(git ls-files '*.py')
        black --check .
        isort --check-only .

    - name: Run tests
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./src/gangagsoc/coverage.xml
        fail_ci_if_error: true